### ISSUE TITLE
ChainProvider ledger: TypeError: this.client.getOfflineSigner is not a function

### ISSUE THREAD

**Issue by risasoft** [cosmology-tech/cosmos-kit#497]
Getting error when trying to sign a txn after connecting ChainProvider to ledger 

```
chain-wallet.js:220 Uncaught (in promise) TypeError: this.client.getOfflineSigner is not a function
    at LedgerChianWallet.initOfflineSigner (chain-wallet.js:220:48)
    at getSigningCosmWasmClient (chain-wallet.js:233:24)
```

├── @cosmjs/amino@0.32.4
├── @cosmjs/cosmwasm-stargate@0.32.4
├── @cosmjs/proto-signing@0.32.4
├── @cosmjs/stargate@0.32.4
├── @cosmos-kit/leap-extension@2.12.2
├── @cosmos-kit/react@2.18.0

**Comment by fmorency** [comment]
I'm also getting this. I tracked down in https://github.com/liftedinit/manifest-app/issues/196#issuecomment-2580804080

**Comment by fmorency** [comment]
@risasoft please test PR above

**Comment by pyramation** [comment]
Thank you!

**Comment by pyramation** [comment]
```
Successfully published:
 - cosmos-kit@2.23.5
 - @cosmos-kit/ledger@2.13.3
 ```
